# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: smashrun-ruby 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "smashrun-ruby".freeze
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Naveed Ahmad".freeze]
  s.date = "2019-09-14"
  s.description = "Ruby gem for Smashrun api".freeze
  s.email = "naveedahmada036@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/workflows/gempush.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/smashrun.rb",
    "lib/smashrun/client.rb",
    "lib/smashrun/configuration.rb",
    "smashrun-ruby.gemspec",
    "test/helper.rb",
    "test/test_smashrun.rb"
  ]
  s.homepage = "http://github.com/naveed-ahmad/smashrun-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Ruby gem for Smashrun api".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth2>.freeze, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<oj>.freeze, ["~> 3.10.2"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    else
      s.add_dependency(%q<oauth2>.freeze, ["~> 1.4.0"])
      s.add_dependency(%q<oj>.freeze, ["~> 3.10.2"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<oauth2>.freeze, ["~> 1.4.0"])
    s.add_dependency(%q<oj>.freeze, ["~> 3.10.2"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
  end
end

